# AUTO-GENERATED by scripts/generate_poses.py
# Do not edit by hand. Regenerated from the published OpenAPI document.
from __future__ import annotations

from typing import Literal

KNOWN_POSES: tuple[str, ...] = (
    "airborne",
    "boxed",
    "britzel",
    "callout",
    "cheer",
    "confidence",
    "crossed",
    "crouching",
    "curl",
    "cute",
    "dab",
    "dead",
    "defeat",
    "delivery",
    "diver",
    "engineer",
    "extended",
    "fired",
    "friendship",
    "gaze",
    "glazed",
    "handstand",
    "idle",
    "idol",
    "kneel",
    "licked",
    "lounge",
    "mojavatar",
    "ninja",
    "point",
    "ponder",
    "pressed",
    "relaxed",
    "scared",
    "shipped",
    "snagged",
    "sprint",
    "tiptoe",
    "toasty",
    "victory",
    "wave",
    "zombie",
)

KnownPose = Literal[
    "airborne",
    "boxed",
    "britzel",
    "callout",
    "cheer",
    "confidence",
    "crossed",
    "crouching",
    "curl",
    "cute",
    "dab",
    "dead",
    "defeat",
    "delivery",
    "diver",
    "engineer",
    "extended",
    "fired",
    "friendship",
    "gaze",
    "glazed",
    "handstand",
    "idle",
    "idol",
    "kneel",
    "licked",
    "lounge",
    "mojavatar",
    "ninja",
    "point",
    "ponder",
    "pressed",
    "relaxed",
    "scared",
    "shipped",
    "snagged",
    "sprint",
    "tiptoe",
    "toasty",
    "victory",
    "wave",
    "zombie",
]


class Poses:
    """Named pose constants, for discoverability and autocompletion."""

    airborne = "airborne"
    boxed = "boxed"
    britzel = "britzel"
    callout = "callout"
    cheer = "cheer"
    confidence = "confidence"
    crossed = "crossed"
    crouching = "crouching"
    curl = "curl"
    cute = "cute"
    dab = "dab"
    dead = "dead"
    defeat = "defeat"
    delivery = "delivery"
    diver = "diver"
    engineer = "engineer"
    extended = "extended"
    fired = "fired"
    friendship = "friendship"
    gaze = "gaze"
    glazed = "glazed"
    handstand = "handstand"
    idle = "idle"
    idol = "idol"
    kneel = "kneel"
    licked = "licked"
    lounge = "lounge"
    mojavatar = "mojavatar"
    ninja = "ninja"
    point = "point"
    ponder = "ponder"
    pressed = "pressed"
    relaxed = "relaxed"
    scared = "scared"
    shipped = "shipped"
    snagged = "snagged"
    sprint = "sprint"
    tiptoe = "tiptoe"
    toasty = "toasty"
    victory = "victory"
    wave = "wave"
    zombie = "zombie"
