# AUTO-GENERATED by scripts/generate_poses.py
# Do not edit by hand. Regenerated from the published OpenAPI document.
from __future__ import annotations

from typing import Literal

KNOWN_POSES: tuple[str, ...] = (
    "cheer",
    "confidence",
    "curl",
    "cute",
    "dab",
    "dead",
    "defeat",
    "friendship",
    "gaze",
    "handstand",
    "idol",
    "kneel",
    "ninja",
    "point",
    "ponder",
    "relaxed",
    "scared",
    "sprint",
    "tiptoe",
    "victory",
    "wave",
    "zombie",
)

KnownPose = Literal[
    "cheer",
    "confidence",
    "curl",
    "cute",
    "dab",
    "dead",
    "defeat",
    "friendship",
    "gaze",
    "handstand",
    "idol",
    "kneel",
    "ninja",
    "point",
    "ponder",
    "relaxed",
    "scared",
    "sprint",
    "tiptoe",
    "victory",
    "wave",
    "zombie",
]


class Poses:
    """Named pose constants, for discoverability and autocompletion."""

    cheer = "cheer"
    confidence = "confidence"
    curl = "curl"
    cute = "cute"
    dab = "dab"
    dead = "dead"
    defeat = "defeat"
    friendship = "friendship"
    gaze = "gaze"
    handstand = "handstand"
    idol = "idol"
    kneel = "kneel"
    ninja = "ninja"
    point = "point"
    ponder = "ponder"
    relaxed = "relaxed"
    scared = "scared"
    sprint = "sprint"
    tiptoe = "tiptoe"
    victory = "victory"
    wave = "wave"
    zombie = "zombie"
