"""Regenerate src/createrington_skin_api/_poses.py from the published OpenAPI document.

Pose names come from the ``pose`` query-parameter enum on POST /v1/render. By
default the live spec is fetched over HTTP; pass a file path or an http(s) URL to
override (for testing or offline runs). No spec file is written to disk.

    python scripts/generate_poses.py [openapi.json | https://host/v1/openapi.json]
"""

from __future__ import annotations

import json
import keyword
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

DEFAULT_SPEC_URL = "https://api.createrington.com/v1/openapi.json"
SPEC_URL_ENV = "SKIN_API_OPENAPI_URL"

SCRIPT_DIR = Path(__file__).resolve().parent
SDK_ROOT = SCRIPT_DIR.parent
OUT_FILE = SDK_ROOT / "src" / "createrington_skin_api" / "_poses.py"


def _resolve_source(argv: list[str]) -> str:
    if len(argv) > 1 and argv[1]:
        return argv[1]
    env = os.environ.get(SPEC_URL_ENV)
    if env:
        return env
    return DEFAULT_SPEC_URL


def _load_spec(source: str) -> bytes:
    path = Path(source)
    if path.is_file():
        return path.read_bytes()
    if source.lower().startswith(("http://", "https://")):
        with urllib.request.urlopen(source, timeout=30) as response:  # noqa: S310
            data: bytes = response.read()
            return data
    raise ValueError(
        f"spec source is neither an existing file nor an http(s) URL: {source}"
    )


def _pose_names(spec: object) -> list[str]:
    if not isinstance(spec, dict):
        raise ValueError("OpenAPI document is not a JSON object")

    render = spec["paths"]["/v1/render"]["post"]["parameters"]
    if not isinstance(render, list):
        raise ValueError("POST /v1/render parameters is not a list")

    pose = next(
        (
            p
            for p in render
            if isinstance(p, dict) and p.get("name") == "pose"
        ),
        None,
    )
    if pose is None:
        raise ValueError("no 'pose' query parameter found on POST /v1/render")

    enum = pose["schema"]["enum"]
    if not isinstance(enum, list):
        raise ValueError("the 'pose' parameter has no enum")

    names = sorted(str(name) for name in enum)
    return names


def _entries(names: list[str]) -> str:
    return "\n".join(f'    "{name}",' for name in names)


def _attrs(names: list[str]) -> str:
    return "\n".join(f'    {name} = "{name}"' for name in names)


def main() -> int:
    source = _resolve_source(sys.argv)

    try:
        spec_bytes = _load_spec(source)
    except (urllib.error.URLError, OSError, ValueError) as exc:
        sys.stderr.write(
            f"could not read the OpenAPI document from {source}: {exc}\n"
        )
        return 1

    try:
        names = _pose_names(json.loads(spec_bytes))
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        sys.stderr.write(
            f"could not read the pose enum from the OpenAPI document: {exc}\n"
        )
        return 1

    if not names:
        sys.stderr.write("the pose enum is empty\n")
        return 1

    # The names become attribute names on the generated ``Poses`` class, so a
    # name that is not a valid identifier (e.g. "full-body") would emit broken
    # Python.
    for name in names:
        if not name.isidentifier() or keyword.iskeyword(name):
            sys.stderr.write(
                f'pose name "{name}" is not a valid identifier and would break '
                "the generated Poses class; update generate_poses.py to handle "
                "it.\n"
            )
            return 1

    body = (
        "# AUTO-GENERATED by scripts/generate_poses.py\n"
        "# Do not edit by hand. Regenerated from the published OpenAPI document.\n"
        "from __future__ import annotations\n\n"
        "from typing import Literal\n\n"
        f"KNOWN_POSES: tuple[str, ...] = (\n{_entries(names)}\n)\n\n"
        f"KnownPose = Literal[\n{_entries(names)}\n]\n\n\n"
        "class Poses:\n"
        '    """Named pose constants, for discoverability and autocompletion."""\n\n'
        f"{_attrs(names)}\n"
    )

    OUT_FILE.write_bytes(body.encode("utf-8"))
    sys.stdout.write(f"generated {OUT_FILE} ({len(names)} poses) from {source}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
